// Service worker — cache-first offline shell (same pattern as the sibling metronome / drum
// auditioner PWAs). Bump CACHE whenever ANY listed asset changes, or installed clients keep
// serving the old files. Cache-first means anything NOT listed in ASSETS is unavailable offline:
// every module + preset JSON + kit WAV + icon must be here. The presets block between the markers
// is regenerated by tools/sync-presets.js.
const CACHE = "euc-v1";

const ASSETS = [
  "./",
  "./index.html",
  "./styles.css",
  "./theme.css",
  "./manifest.webmanifest",

  "./js/main.js",
  "./js/player.js",
  "./js/ringView.js",
  "./js/controlsPanel.js",
  "./js/presetStore.js",
  "./js/patternStore.js",
  "./js/euclid.js",
  "./js/generators.js",
  "./js/accentModel.js",
  "./js/laneModel.js",
  "./js/grooveModel.js",
  "./js/patternModel.js",
  "./js/exportModel.js",
  "./js/presetModel.js",
  "./js/smf.js",
  "./js/fileSink.js",
  "./js/engine/midiParse.js",
  "./js/engine/clickModel.js",
  "./js/engine/drumModel.js",
  "./js/engine/drumKits.js",

  // presets:start
  "./presets/index.json",
  "./presets/rock-four-on-the-floor.json",
  "./presets/rock-half-time.json",
  "./presets/pop-boots-n-cats.json",
  "./presets/pop-dembow.json",
  "./presets/jazzy-take-five.json",
  "./presets/jazzy-swung-ride.json",
  "./presets/ballad-slow-six-eight.json",
  "./presets/ballad-sparse.json",
  "./presets/latin-bossa-nova.json",
  "./presets/latin-son-tresillo.json",
  "./presets/world-bembe-bell.json",
  "./presets/world-samba.json",
  // presets:end

  "./assets/drums/kits/kit4/kick.wav",
  "./assets/drums/kits/kit4/snare.wav",
  "./assets/drums/kits/kit4/closedHat.wav",
  "./assets/drums/kits/kit4/openHat.wav",
  "./assets/drums/kits/kit4/lowTom.wav",
  "./assets/drums/kits/kit4/midTom.wav",
  "./assets/drums/kits/kit4/highTom.wav",
  "./assets/drums/kits/kit4/crash.wav",
  "./assets/drums/kits/kit4/ride.wav",
  "./assets/drums/kits/kit4/clap.wav",
  "./assets/drums/kits/kit4/hiConga.wav",
  "./assets/drums/kits/kit4/loConga.wav",

  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/maskable-512.png",
  "./icons/apple-touch-icon.png"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((resp) => {
          if (resp && resp.status === 200 && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return resp;
        })
        .catch(() => {
          if (req.mode === "navigate") {
            return caches.match("./index.html", { ignoreSearch: true })
              .then((c) => c || caches.match("./", { ignoreSearch: true }));
          }
        });
    })
  );
});
